# Generated by Django 6.0.6 on 2026-06-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUT', 'Em manutenção'), ('INATIVO', 'Inativo')], default='ATIVO'),
        ),
    ]
