# Generated by Django 6.0.6 on 2026-06-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_alter_equipamento_obs_alter_equipamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='obra',
            field=models.CharField(choices=[('OBRA_URUACU', 'OBRA BR 153 - URUAÇU - GO'), ('OBRA_RIALMA', 'OBRA BR 153 - RIALMA - GO')], default='OBRA_URUACU'),
        ),
    ]
