# Generated by Django 6.0.6 on 2026-06-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_equipamento_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='local',
            field=models.CharField(choices=[('SOLO', 'Laboraório De Solo'), ('ASFALTO', 'Laboratório De Asfalto')], default=''),
        ),
    ]
